### ISSUE TITLE
Different Constants for Each Robot

### ISSUE THREAD

**Issue by ianof** [frc5687/2017-protobot#52]
Add the ability to detect what robot the code is running on, and use the appropriate set of constants (mostly just pot values)

**Comment by BenBernardCIS** [comment]
Here's my suggestion: we only need this for the pots now, so I suggest a more manual approach:

In constants:
- [ ] Add a static boolean "isTony" defaulting to true
- [ ] Add a static double "pickConstant" with double parameters tonyValie and protobotValue, and returning one or the other based on the value of isTony.
In Robot:
- [ ]  At the end of robotInit, add a call to set Constants.isTony based on PDP.isTony()

In each place where we use bot-specific constants, replace with a call to Constants.pickConstant.
