### ISSUE TITLE
Pincers Code

### ISSUE THREAD

**Issue by ianof** [frc5687/2017-protobot#61]

**Comment by BenBernardCIS** [comment]
- Add subsystem
- - Victor for lifter motor
- - Doublesolenoid for pneumatics piston
- - Pot for angle
- - Hall effects?
- Add commands
- - DropPincers - PID to run motor down to target pot angle
- - LiftPincers - PID to run motor up to target pot angle
- - ClosePincers - Fire doublesolenoid
- - OpenPincers - Fire doublesolenoid
- - Wire these to OC or Logitech buttons
